usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

pagina_ayuda:
    pattern:  /ayuda
    defaults: { _controller: OfertaBundle:Default:ayuda}
